In [ ]:
import numpy as np
import pandas as pd

# Dataframe is a 2D table format data. 

# A) Creating a DataFrame from a List

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

col = ['Name','Age','City','Salary'] # we are providing labels here for the data frame

df_from_list = pd.DataFrame(data_list,columns=col)

In [2]:
df_from_list

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
# Creating a DataFrame using Dictionary

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df_from_dict = pd.DataFrame(data) # Here also The labels are given as per the DICT KEYS

In [4]:
df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection and Indexing

In [6]:
df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
# SELECTING A SINGLE ROW
df_from_dict['Name'] # PROVIDE COL NAME

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [9]:
# SELECTING MULTIPLE ROW
df_from_dict[['Age','Salary']] #give col name in a nested list format

   Age  Salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

## Creating a new column

In [10]:
df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
#Adding a new col as Country

# We need to provide data for each row else value error is occured
#df_from_dict["Country"] = ["India", "Korea"]  #ValueError: Length of values (2) does not match length of index (4)

df_from_dict['Country'] = ['India','Korea','Japan','Ireland']
df_from_dict

    Name  Age      City  Salary  Country
0   John   28  New York   65000    India
1   Anna   34     Paris   70000    Korea
2  Peter   29    Berlin   62000    Japan
3  Linda   42    London   85000  Ireland

## Removing a Column from DataFrame

In [13]:
df_from_dict

    Name  Age      City  Salary  Country
0   John   28  New York   65000    India
1   Anna   34     Paris   70000    Korea
2  Peter   29    Berlin   62000    Japan
3  Linda   42    London   85000  Ireland

In [15]:
# We remove the country col
# we need to provide AXIS for finding the col , by Default axis=0 
df_from_dict.drop('Country',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
# IMPORTANT : but if we again print the dataframe , we see country is still present into it. 
# Because it only show the snapshot or a copy of ACTUAL DATAFRAME and it remain in the storage
df_from_dict

    Name  Age      City  Salary  Country
0   John   28  New York   65000    India
1   Anna   34     Paris   70000    Korea
2  Peter   29    Berlin   62000    Japan
3  Linda   42    London   85000  Ireland

In [21]:
# Now if we want to completely remove the country column , we use INPLACE = True in .drop()
df_from_dict.drop('Country', axis=1, inplace=True)

KeyError: "['Country'] not found in axis"

In [22]:
df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
# to remove multiple rows 
df_from_dict.drop(['Salary','City'], axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

## Selecting rows and subset of rows and columns

In [24]:
df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
#for Selecting rows we use df.loc   or df.iloc

df_from_dict.loc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [27]:
df_from_dict.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [29]:
df_from_dict.loc[[0,3]]

    Name  Age      City  Salary
0   John   28  New York   65000
3  Linda   42    London   85000

In [30]:
#NOW accessing some subset or row and col

df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
df_from_dict.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

## Conditional Selection

In [36]:
df_from_dict

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
# Select person whose salary is above 66000 and having age more than 30

df_from_dict[(df_from_dict['Age'] > 30) & (df_from_dict['Salary'] > 66000)]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000