## Finding Missing Values



### NOTE: YOU NEED TO GIVE inplace=True FOR ACTUAL MODIFICATION OF TABLE. WITHOUT IT , MODIFICATION ONLY DONE ON COPY OF REAL DATA

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [3]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
# Now if we want a bool table to know about nan data , we use .isna()

df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
# now if we want to know how many NaN values are in each col . we use .isna().sum()
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [6]:
# if we want to know is there any column with no NaN values . we use .isna().any()

df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

## Removing Missing Values 
### Removal of missing values happens using rows of dataframe, which means row-wise removal happens.

In [7]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [8]:
# dropna() is used to remove

df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [9]:
# dropna(thresh=3) here thresh har ek row me jake check karta hai ki ATLEAST 3 NON NULL values toh present honi chahiye. if present hai toh vo rows ko conserve karo
# aur agar 3 non null values se kam ho toh delete kardo.

df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## Filling Missing Values

In [10]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [11]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [12]:
fill_values = {'A':10,'B':20,'C':30,'D':40}

df.fillna(value=fill_values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  40.0
2  10.0  3   3.0  40.0
3   4.0  4  30.0  40.0
4   5.0  5  30.0   5.0

In [13]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0